# This is a basic workflow to help you get started with Actions


name: ExecuteProcess
on:

 # push:
  #  branches:
   #   - main
    #paths-ignore:
     # - '.gitignore'
      #- '.github/workflows/**'

# Controls when the workflow will run
#on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
#  push:
#    branches: [ "main" ]
#  pull_request:
#    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
        inputs: 
          executefilename:
            description: 'executefilename'     
            required: true
            default: ''

# A workflow run is made up of one or more jobs that can run sequentially or in parallel

jobs:
  # This workflow contains a single job called "build"

 
          
  executeProcess:
      # The type of runner that the job will run on
    runs-on: [self-hosted, linux, X64]
   
        
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
        #with:
        #  fetch-depth: 0
        #  path: INT-001

      - name: Changed Files
        id: changed-files
        uses: tj-actions/changed-files@v37.5.2
        #with:
        #  path: INT-001
        
      # Runs a single command using the runners shell
      #- name: Run a one-line script
      #  run:  cat ${{ github.workspace }}/README.md

      # Runs a set of commands using the runners shell
      - name: Execute Process
        run: |
            echo "name: ${{ inputs.executefilename}}" 
            echo "$(pwd)"
            file=$(<${{ inputs.executefilename}})
            echo "file contents are .. $file"
            atomName1=$(grep '^atomName=' ${{ inputs.executefilename}} | cut -f2 -d'=')
            processName1=$(grep '^processName=' ${{ inputs.executefilename}} | cut -f2 -d'=')
            componentId1=$(grep '^componentId=' ${{ inputs.executefilename}} | cut -f2 -d'=')
            echo "p name is.. $processName1"
            echo "a name is.. $atomName1"
            echo "c name is.. $componentId1"
            export WD=~/cicd/boomicicd-cli/cli/scripts
            export WORKSPACE=~/cicd/boomicicd-cli/cli/scripts
            ~/cicd/boomicicd-cli/cli/scripts/bin/common.sh
            ~/cicd/boomicicd-cli/cli/scripts/executeProc.sh processName=$processName1 atomName=$atomName1 componentId=$componentId1 


 
